import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTriageReportId1780017557522 implements MigrationInterface {
    name = 'AddTriageReportId1780017557522'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "saved_locations" DROP CONSTRAINT "FK_saved_locations_user"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "bookings_user_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" DROP CONSTRAINT "hospital_capabilities_hospital_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "dispatches" DROP CONSTRAINT "dispatches_ambulance_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "dispatches" DROP CONSTRAINT "dispatches_booking_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "dispatches" DROP CONSTRAINT "dispatches_driver_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "dispatches" DROP CONSTRAINT "dispatches_hospital_id_fkey"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_user_id_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_saved_locations_user_id"`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" DROP CONSTRAINT "hospital_capabilities_hospital_id_capability_type_key"`);
        await queryRunner.query(`CREATE TYPE "public"."triage_reports_emergencytype_enum" AS ENUM('CARDIAC', 'TRAUMA', 'NEURO')`);
        await queryRunner.query(`CREATE TABLE "triage_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "emergencyType" "public"."triage_reports_emergencytype_enum" NOT NULL, "breathing" boolean NOT NULL, "bleeding" boolean NOT NULL, "conscious" boolean NOT NULL, "painLevel" integer NOT NULL, "pregnancy" boolean NOT NULL, CONSTRAINT "PK_8458c7ea18a26ed1f1d663be2b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "scheduled_time"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "assigned_at"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "started_at"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "cancellation_reason"`);
        await queryRunner.query(`ALTER TABLE "hospitals" DROP COLUMN "is_verified"`);
        await queryRunner.query(`ALTER TABLE "hospitals" DROP COLUMN "last_status_update"`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "triage_report_id" uuid`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "UQ_63323f8c510a3d122c154b2bc68" UNIQUE ("triage_report_id")`);
        await queryRunner.query(`ALTER TYPE "public"."user_role" RENAME TO "user_role_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('USER', 'DRIVER', 'HOSPITAL', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'USER'`);
        await queryRunner.query(`DROP TYPE "public"."user_role_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'USER'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_verified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."booking_status" RENAME TO "booking_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_status_enum" AS ENUM('PENDING', 'CREATED', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" TYPE "public"."bookings_status_enum" USING "status"::"text"::"public"."bookings_status_enum"`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."booking_status_old"`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "booking_type"`);
        await queryRunner.query(`DROP TYPE "public"."booking_type"`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "booking_type" character varying(20) NOT NULL DEFAULT 'EMERGENCY'`);
        await queryRunner.query(`ALTER TYPE "public"."severity_level" RENAME TO "severity_level_old"`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_severity_enum" AS ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "severity" TYPE "public"."bookings_severity_enum" USING "severity"::"text"::"public"."bookings_severity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."severity_level_old"`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ambulances" DROP COLUMN "vehicle_type"`);
        await queryRunner.query(`DROP TYPE "public"."ambulance_type"`);
        await queryRunner.query(`ALTER TABLE "ambulances" ADD "vehicle_type" character varying(30) NOT NULL DEFAULT 'BASIC'`);
        await queryRunner.query(`ALTER TYPE "public"."ambulance_status" RENAME TO "ambulance_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."ambulances_status_enum" AS ENUM('AVAILABLE', 'RESERVED', 'BUSY', 'MAINTENANCE', 'OFFLINE', 'PENDING')`);
        await queryRunner.query(`ALTER TABLE "ambulances" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ambulances" ALTER COLUMN "status" TYPE "public"."ambulances_status_enum" USING "status"::"text"::"public"."ambulances_status_enum"`);
        await queryRunner.query(`ALTER TABLE "ambulances" ALTER COLUMN "status" SET DEFAULT 'AVAILABLE'`);
        await queryRunner.query(`DROP TYPE "public"."ambulance_status_old"`);
        await queryRunner.query(`ALTER TABLE "ambulances" ALTER COLUMN "status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ambulances" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ambulances" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ALTER COLUMN "hospital_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."capability_type" RENAME TO "capability_type_old"`);
        await queryRunner.query(`CREATE TYPE "public"."hospital_capabilities_capability_type_enum" AS ENUM('ER', 'ICU', 'CARDIAC', 'TRAUMA', 'NEURO', 'OB')`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ALTER COLUMN "capability_type" TYPE "public"."hospital_capabilities_capability_type_enum" USING "capability_type"::"text"::"public"."hospital_capabilities_capability_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."capability_type_old"`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."hospital_service_status"`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ADD "status" character varying(20) NOT NULL DEFAULT 'ACCEPTING'`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ALTER COLUMN "capacity" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ALTER COLUMN "current_load" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."hospital_service_status" RENAME TO "hospital_service_status_old"`);
        await queryRunner.query(`CREATE TYPE "public"."hospitals_service_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'MAINTENANCE')`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "service_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "service_status" TYPE "public"."hospitals_service_status_enum" USING "service_status"::"text"::"public"."hospitals_service_status_enum"`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "service_status" SET DEFAULT 'ACTIVE'`);
        await queryRunner.query(`DROP TYPE "public"."hospital_service_status_old"`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "service_status" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "total_beds" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "available_beds" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dispatches" ALTER COLUMN "booking_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dispatches" ALTER COLUMN "ambulance_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dispatches" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."dispatch_status"`);
        await queryRunner.query(`ALTER TABLE "dispatches" ADD "status" character varying(30) NOT NULL DEFAULT 'DISPATCHED'`);
        await queryRunner.query(`ALTER TABLE "dispatches" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dispatches" ALTER COLUMN "updated_at" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "created_at" SET NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_3411322e212076d1ac1a71e6ed" ON "bookings" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_48b267d894e32a25ebde4b207a" ON "bookings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_64cd97487c5c42806458ab5520" ON "bookings" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6d85d28cdedd13e7357b10d14" ON "ambulances" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1a129f9fcb76bd48afe5ae5c1b" ON "hospital_capabilities" ("hospital_id", "capability_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_93c7cdee63463baa4898926f87" ON "hospitals" ("service_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_49f993f31aa3b1b3a38c93276b" ON "dispatches" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c37cc769c7ee3bd399e273abe0" ON "dispatches" ("hospital_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f96a69fe02faa8b3cc21894319" ON "dispatches" ("ambulance_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e294f2f37a067cdc9ddb08a944" ON "dispatches" ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd2726fd31b35443f2245b93ba" ON "audit_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7421efc125d95e413657efa3c6" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`ALTER TABLE "saved_locations" ADD CONSTRAINT "FK_355266d32f3a94cbefb8ded8874" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_64cd97487c5c42806458ab5520c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_63323f8c510a3d122c154b2bc68" FOREIGN KEY ("triage_report_id") REFERENCES "triage_reports"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ADD CONSTRAINT "FK_c90321167d0ed2904e5dc5d2bfc" FOREIGN KEY ("hospital_id") REFERENCES "hospitals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispatches" ADD CONSTRAINT "FK_e294f2f37a067cdc9ddb08a944a" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispatches" ADD CONSTRAINT "FK_f96a69fe02faa8b3cc21894319c" FOREIGN KEY ("ambulance_id") REFERENCES "ambulances"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispatches" ADD CONSTRAINT "FK_c37cc769c7ee3bd399e273abe07" FOREIGN KEY ("hospital_id") REFERENCES "hospitals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "dispatches" DROP CONSTRAINT "FK_c37cc769c7ee3bd399e273abe07"`);
        await queryRunner.query(`ALTER TABLE "dispatches" DROP CONSTRAINT "FK_f96a69fe02faa8b3cc21894319c"`);
        await queryRunner.query(`ALTER TABLE "dispatches" DROP CONSTRAINT "FK_e294f2f37a067cdc9ddb08a944a"`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" DROP CONSTRAINT "FK_c90321167d0ed2904e5dc5d2bfc"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_63323f8c510a3d122c154b2bc68"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_64cd97487c5c42806458ab5520c"`);
        await queryRunner.query(`ALTER TABLE "saved_locations" DROP CONSTRAINT "FK_355266d32f3a94cbefb8ded8874"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7421efc125d95e413657efa3c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd2726fd31b35443f2245b93ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e294f2f37a067cdc9ddb08a944"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f96a69fe02faa8b3cc21894319"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c37cc769c7ee3bd399e273abe0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_49f993f31aa3b1b3a38c93276b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93c7cdee63463baa4898926f87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a129f9fcb76bd48afe5ae5c1b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6d85d28cdedd13e7357b10d14"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64cd97487c5c42806458ab5520"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48b267d894e32a25ebde4b207a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3411322e212076d1ac1a71e6ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dispatches" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dispatches" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dispatches" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."dispatch_status" AS ENUM('AT_HOSPITAL', 'AT_PICKUP', 'CANCELLED', 'COMPLETED', 'DISPATCHED', 'EN_ROUTE_HOSPITAL', 'EN_ROUTE_PICKUP')`);
        await queryRunner.query(`ALTER TABLE "dispatches" ADD "status" "public"."dispatch_status" DEFAULT 'DISPATCHED'`);
        await queryRunner.query(`ALTER TABLE "dispatches" ALTER COLUMN "ambulance_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dispatches" ALTER COLUMN "booking_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "available_beds" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "total_beds" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "service_status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."hospital_service_status_old" AS ENUM('ACCEPTING', 'DIVERT', 'LIMITED')`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "service_status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "service_status" TYPE "public"."hospital_service_status_old" USING "service_status"::"text"::"public"."hospital_service_status_old"`);
        await queryRunner.query(`ALTER TABLE "hospitals" ALTER COLUMN "service_status" SET DEFAULT 'ACCEPTING'`);
        await queryRunner.query(`DROP TYPE "public"."hospitals_service_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."hospital_service_status_old" RENAME TO "hospital_service_status"`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ALTER COLUMN "current_load" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ALTER COLUMN "capacity" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."hospital_service_status" AS ENUM('ACCEPTING', 'DIVERT', 'LIMITED')`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ADD "status" "public"."hospital_service_status" DEFAULT 'ACCEPTING'`);
        await queryRunner.query(`CREATE TYPE "public"."capability_type_old" AS ENUM('CARDIAC', 'ER', 'ICU', 'NEURO', 'OB', 'TRAUMA')`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ALTER COLUMN "capability_type" TYPE "public"."capability_type_old" USING "capability_type"::"text"::"public"."capability_type_old"`);
        await queryRunner.query(`DROP TYPE "public"."hospital_capabilities_capability_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."capability_type_old" RENAME TO "capability_type"`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ALTER COLUMN "hospital_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ambulances" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ambulances" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "ambulances" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."ambulance_status_old" AS ENUM('AVAILABLE', 'BUSY', 'MAINTENANCE', 'OFFLINE')`);
        await queryRunner.query(`ALTER TABLE "ambulances" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "ambulances" ALTER COLUMN "status" TYPE "public"."ambulance_status_old" USING "status"::"text"::"public"."ambulance_status_old"`);
        await queryRunner.query(`ALTER TABLE "ambulances" ALTER COLUMN "status" SET DEFAULT 'AVAILABLE'`);
        await queryRunner.query(`DROP TYPE "public"."ambulances_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."ambulance_status_old" RENAME TO "ambulance_status"`);
        await queryRunner.query(`ALTER TABLE "ambulances" DROP COLUMN "vehicle_type"`);
        await queryRunner.query(`CREATE TYPE "public"."ambulance_type" AS ENUM('ADVANCED', 'BASIC', 'CRITICAL_CARE')`);
        await queryRunner.query(`ALTER TABLE "ambulances" ADD "vehicle_type" "public"."ambulance_type" DEFAULT 'BASIC'`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."severity_level_old" AS ENUM('CRITICAL', 'HIGH', 'LOW', 'MEDIUM')`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "severity" TYPE "public"."severity_level_old" USING "severity"::"text"::"public"."severity_level_old"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_severity_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."severity_level_old" RENAME TO "severity_level"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "booking_type"`);
        await queryRunner.query(`CREATE TYPE "public"."booking_type" AS ENUM('EMERGENCY', 'SCHEDULED')`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "booking_type" "public"."booking_type" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."booking_status_old" AS ENUM('ASSIGNED', 'CANCELLED', 'COMPLETED', 'CREATED', 'IN_PROGRESS')`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" TYPE "public"."booking_status_old" USING "status"::"text"::"public"."booking_status_old"`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "status" SET DEFAULT 'CREATED'`);
        await queryRunner.query(`DROP TYPE "public"."bookings_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."booking_status_old" RENAME TO "booking_status"`);
        await queryRunner.query(`ALTER TABLE "bookings" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updated_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "created_at" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "email_verified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "is_active" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`CREATE TYPE "public"."user_role_old" AS ENUM('ADMIN', 'DRIVER', 'HOSPITAL', 'USER')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."user_role_old" USING "role"::"text"::"public"."user_role_old"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."user_role_old" RENAME TO "user_role"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "UQ_63323f8c510a3d122c154b2bc68"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP COLUMN "triage_report_id"`);
        await queryRunner.query(`ALTER TABLE "hospitals" ADD "last_status_update" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "hospitals" ADD "is_verified" boolean DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "cancellation_reason" text`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "started_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "assigned_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD "scheduled_time" TIMESTAMP`);
        await queryRunner.query(`DROP TABLE "triage_reports"`);
        await queryRunner.query(`DROP TYPE "public"."triage_reports_emergencytype_enum"`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ADD CONSTRAINT "hospital_capabilities_hospital_id_capability_type_key" UNIQUE ("hospital_id", "capability_type")`);
        await queryRunner.query(`CREATE INDEX "IDX_saved_locations_user_id" ON "saved_locations" ("user_id") `);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispatches" ADD CONSTRAINT "dispatches_hospital_id_fkey" FOREIGN KEY ("hospital_id") REFERENCES "hospitals"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispatches" ADD CONSTRAINT "dispatches_driver_id_fkey" FOREIGN KEY ("driver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispatches" ADD CONSTRAINT "dispatches_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dispatches" ADD CONSTRAINT "dispatches_ambulance_id_fkey" FOREIGN KEY ("ambulance_id") REFERENCES "ambulances"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hospital_capabilities" ADD CONSTRAINT "hospital_capabilities_hospital_id_fkey" FOREIGN KEY ("hospital_id") REFERENCES "hospitals"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "bookings_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_locations" ADD CONSTRAINT "FK_saved_locations_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
